spring.application.name=jpa
spring.jpa.generate-ddl=true

# --- P6Spy Configuration (The "Pretty" SQL with values) ---
#decorator.datasource.p6spy.enable-logging=true
#decorator.datasource.p6spy.multiline=true
#decorator.datasource.p6spy.logging=slf4j

# --- Hibernate Cleanup (Disable its internal logging to avoid duplicates) ---
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.properties.hibernate.highlight_sql=true

# --- Docker ---
spring.docker.compose.host=192.168.1.10
spring.docker.compose.skip.in-tests=false